In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df =pd.read_csv('Student_Performance - Student_Performance.csv')

In [3]:
df.head()

Hours Studied  Previous Scores Extracurricular Activities  Sleep Hours  \
0              7               99                        Yes            9   
1              4               82                         No            4   
2              8               51                        Yes            7   
3              5               52                        Yes            5   
4              7               75                         No            8   

   Sample Question Papers Practiced  Performance Index  
0                                 1                 91  
1                                 2                 65  
2                                 2                 45  
3                                 2                 36  
4                                 5                 66

In [4]:
df.describe(include='all')

Hours Studied  Previous Scores Extracurricular Activities  \
count    10000.000000     10000.000000                      10000   
unique            NaN              NaN                          2   
top               NaN              NaN                         No   
freq              NaN              NaN                       5052   
mean         4.992900        69.445700                        NaN   
std          2.589309        17.343152                        NaN   
min          1.000000        40.000000                        NaN   
25%          3.000000        54.000000                        NaN   
50%          5.000000        69.000000                        NaN   
75%          7.000000        85.000000                        NaN   
max          9.000000        99.000000                        NaN   

         Sleep Hours  Sample Question Papers Practiced  Performance Index  
count   10000.000000                      10000.000000       10000.000000  
unique           NaN                               NaN                NaN  
top              NaN                               NaN                NaN  
freq             NaN                               NaN                NaN  
mean        6.530600                          4.583300          55.224800  
std         1.695863                          2.867348          19.212558  
min         4.000000                          0.000000          10.000000  
25%         5.000000                          2.000000          40.000000  
50%         7.000000                          5.000000          55.000000  
75%         8.000000                          7.000000          71.000000  
max         9.000000                          9.000000         100.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype 
---  ------                            --------------  ----- 
 0   Hours Studied                     10000 non-null  int64 
 1   Previous Scores                   10000 non-null  int64 
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64 
 4   Sample Question Papers Practiced  10000 non-null  int64 
 5   Performance Index                 10000 non-null  int64 
dtypes: int64(5), object(1)
memory usage: 468.9+ KB


ENCODING

In [6]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes':1,'No':0})

In [7]:
df['Extracurricular Activities']

0       1
1       0
2       1
3       1
4       0
       ..
9995    1
9996    1
9997    1
9998    1
9999    0
Name: Extracurricular Activities, Length: 10000, dtype: int64

DIVIDE DATASET INTO INPUT AND OUTPUT

In [8]:
input = df.drop('Performance Index',axis=1)

In [9]:
input

Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
0                 7               99                           1            9   
1                 4               82                           0            4   
2                 8               51                           1            7   
3                 5               52                           1            5   
4                 7               75                           0            8   
...             ...              ...                         ...          ...   
9995              1               49                           1            4   
9996              7               64                           1            8   
9997              6               83                           1            8   
9998              9               97                           1            7   
9999              7               74                           0            8   

      Sample Question Papers Practiced  
0                                    1  
1                                    2  
2                                    2  
3                                    2  
4                                    5  
...                                ...  
9995                                 2  
9996                                 5  
9997                                 5  
9998                                 0  
9999                                 1  

[10000 rows x 5 columns]

In [10]:
output = df['Performance Index']
output

0       91
1       65
2       45
3       36
4       66
        ..
9995    23
9996    58
9997    74
9998    95
9999    64
Name: Performance Index, Length: 10000, dtype: int64

SCALLING THE DATA

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [12]:
x_train,x_test,y_train,y_test = train_test_split(input,output,test_size = 0.25,random_state=0)

In [13]:
x_train.shape

(7500, 5)

In [14]:
y_train.shape

(7500,)

In [15]:
x_test.shape

(2500, 5)

In [16]:
y_test.shape

(2500,)

In [17]:
scaled = StandardScaler()

In [18]:
scaled_train = scaled.fit_transform(x_train)
scaled_test = scaled.transform(x_test)

In [19]:
scaled_test

array([[-0.3772178 , -0.14349687, -0.99813507,  1.4490835 , -0.55156609],
       [ 1.16412434, -0.54558833, -0.99813507, -1.49588893,  0.8415121 ],
       [ 0.39345327,  1.17766078, -0.99813507, -0.90689444,  0.49324255],
       ...,
       [ 1.16412434, -1.1200047 , -0.99813507,  0.86008902,  0.8415121 ],
       [ 0.77878881,  0.20115295,  1.00186841,  1.4490835 ,  0.144973  ],
       [ 0.39345327,  1.34998569,  1.00186841,  1.4490835 ,  0.144973  ]])

In [20]:
scaled_train

array([[ 0.77878881, -0.89023815, -0.99813507,  0.86008902, -0.55156609],
       [-0.76255333, -0.20093851, -0.99813507, -1.49588893,  0.49324255],
       [-1.14788887,  1.52231061,  1.00186841,  1.4490835 ,  1.18978165],
       ...,
       [-1.5332244 ,  0.37347787,  1.00186841, -0.31789996,  0.144973  ],
       [-0.3772178 , -1.46465452, -0.99813507, -1.49588893,  1.18978165],
       [ 1.16412434,  0.77556932,  1.00186841,  0.86008902, -1.24810519]])

MODELING

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
model = LinearRegression()

In [23]:
model.fit(scaled_train,y_train)

LinearRegression()

In [24]:
y_train_scaled = model.predict(scaled_train)
y_train_scaled

array([45.28859942, 44.76411194, 75.90671162, ..., 50.67535647,
       25.57646887, 77.97218025])

In [25]:
model.coef_

array([ 7.40141709, 17.73933107,  0.32952253,  0.81104029,  0.54240269])

In [26]:
model.intercept_

55.24719999999999

In [27]:
y_test_scaled = model.predict(scaled_test)
y_test_scaled

array([50.45690146, 53.09930205, 78.25332644, ..., 44.82033293,
       66.16369669, 83.69119201])

In [28]:
from sklearn.metrics import mean_squared_error

In [29]:
train_mse = mean_squared_error(y_train,y_train_scaled)
train_mse

4.175365881221571

In [30]:
rmse = np.sqrt(train_mse)
rmse

2.0433712049506743

In [31]:
test_mse = mean_squared_error(y_test,y_test_scaled)
test_mse

4.0827039600401065

In [32]:
rmse = np.sqrt(test_mse)
rmse

2.0205702066595226

**R2 SCORE**

In [33]:
model.score(scaled_train,y_train)

0.9888387996981384

SAVING DATA BY JOBLIB

In [34]:
import joblib
joblib.dump(model,'STUDENT_PERFORMANCE.pkl')

['STUDENT_PERFORMANCE.pkl']

In [35]:
joblib.dump(scaled,'SCALER.pkl')

['SCALER.pkl']

In [36]:
scaler = joblib.load('SCALER.pkl')

In [37]:
model = joblib.load('STUDENT_PERFORMANCE.pkl')